language: node_js

node_js:
  - '8.10'

script:
  - cd skill-1
  - npm install
  - cd ../skill-2
  - npm install
  - cd ../skill-3
  - npm install

# before_deploy:
#   - pwd
#   - zip -r kochi-skill.zip ${TRAVIS_BUILD_DIR}/skill-1/

deploy:
  - provider: lambda
    function_name: "kochi-city-guide"
    region: $AWS_REGION
    role: $AWS_ROLE
    runtime: "nodejs8.10"
    handler_name: "handler"
    zip: ${TRAVIS_BUILD_DIR}/skill-1/
    on:	
      condition: $DEPLOYMENT = kochi-city-guide
  - provider: lambda	
    function_name: "github-skill"	
    region: $AWS_REGION
    role: $AWS_ROLE
    runtime: "nodejs8.10"	
    handler_name: "handler"	
    zip: ${TRAVIS_BUILD_DIR}/skill-2/	
    on:	
      condition: $DEPLOYMENT = github-skill	
  - provider: lambda	
    function_name: "hacker-news"	
    region: $AWS_REGION
    role: $AWS_ROLE
    runtime: "nodejs8.10"	
    handler_name: "handler"	
    zip: ${TRAVIS_BUILD_DIR}/skill-3/	
    on:	
      condition: $DEPLOYMENT = hacker-news
