language: node_js

node_js:
  - '8.10'

script:
  - npm install

before_deploy:
  - zip -r kochi-skill.zip ${REPO}/skill-1/

deploy:
  provider: lambda
  function_name: "kochi-city-guide"
  region: "us-east-1"
  role: "arn:aws:iam::057063438519:role/aws-serverless-repository-alexaskillskitnodejsfact-37G6OSYYKEY"
  runtime: "nodejs8.10"
  handler_name: "index.handler"
  zip: "kochi-skills.zip"