language: node_js

node_js:
  - '8.10'

script:
  - cd skill-1
  - npm install

# before_deploy:
#   - pwd
#   - zip -r kochi-skill.zip ${TRAVIS_BUILD_DIR}/skill-1/

deploy:
  provider: lambda
  function_name: "kochi-city-guide"
  region: "us-east-1"
  role: "arn:aws:iam::057063438519:role/aws-serverless-repository-alexaskillskitnodejsfact-37G6OSYYKEY"
  runtime: "nodejs8.10"
  handler_name: "handler"
  zip: ${TRAVIS_BUILD_DIR}/skill-1/
  on:
    condition: $DEPLOYMENT = kochi-city-guide

deploy:
  provider: lambda
  function_name: "github-skill"
  region: "us-east-1"
  role: "arn:aws:iam::057063438519:role/aws-serverless-repository-alexaskillskitnodejsfact-37G6OSYYKEY"
  runtime: "nodejs8.10"
  handler_name: "handler"
  zip: ${TRAVIS_BUILD_DIR}/skill-2/
  on:
    condition: $DEPLOYMENT = github-skill
